name: Test
on: [push, pull_request]
jobs:
  dash_tests:
    name: iOS
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ios
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - run: bundle install --path vendor/bundle
      - run: pod install
      - run: /usr/libexec/PlistBuddy -c 'Save' test Dash/GoogleService-Info.plist
      - run: /usr/libexec/PlistBuddy -c 'Save' test ShareExtension/GoogleService-Info.plist
      - run: bundle exec rake test
